print("Hello")
print("This message")
print("is printed using")
print("VS code ide\n")

print("Johny Johny")
print("Yes,Papa?")
print("Eating Sugar?")
#print("Yes,Papa!")
print("No,Papa!")
print("Telling Lies?")
#print("Yes,Papa!")
print("No,Papa!")
print("Open your mouth")
print("Ah, ah, ah!\n")